###GET /todos -should fetch all objects in the todos collectio
GET http://localhost:8081/todos
Content-Type: application/json

###GET /todos/:id -gets a specific object in the todos collection
GET http://localhost:8081/todos/1
Content-Type: application/json

###POST /todos -adds a new object in the todos collection
POST http://localhost:8081/todos
Content-Type: application/json

{
  "_id" : 1,
  "task": "Hello World", 
  "checked": false
}

###PATCH /todos/:id -updates an existing object in the todos collection
PATCH http://localhost:8081/todos/1
Content-Type: application/json

{
 "checked": true
}

###PATCH /todos/:id -update check
PATCH http://localhost:8081/todos/1
Content-Type: application/json

{
 "checked": ""
}

###DELETE /todos/:id delete an object in the todos collection
DELETE  http://localhost:8081/todos/1
Content-Type: application/json

###DELETE /todos
DELETE  http://localhost:8081/todos
Content-Type: application/json

